"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import Nav from './components/Nav';
import { AppContextProvider } from '@/context/context';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AppContextProvider>
        <Nav/>
        {children}
      </AppContextProvider>
      </body>
    </html>
  )
}
